version: '3'

services:
  mongodb:
    image: mongodb-base
    volumes: 
      - /home/jnunesju/projects/docker/mongodb/data:/data/db
    ports:
      - 27017:27017
    
  app:
    image: app-base
    volumes: 
      - /home/jnunesju/development/nodejs/containerapp:/src
    ports:
      - 3000:3000
    deploy:
      mode: replicated
      replicas: 3
    



